//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrabCarMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pax
    {
        public int id { get; set; }
        public string userName { get; set; }
        public string pass { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string photo { get; set; }
        public string mob { get; set; }
        public string email { get; set; }
        public string NidNo { get; set; }
        public string NidFront { get; set; }
        public string NidBack { get; set; }
        public string EmerPName { get; set; }
        public string EmerPNo { get; set; }
        public string WhereDesh { get; set; }
    }
}
